### ISSUE TITLE
[Request] Allowing export the db to binary file from vfs

### ISSUE THREAD

**Issue by khanhicetea** [subframe7536/sqlite-wasm#1]
Hi, thanks for the library. So far so good :)

One feature local-db need is ability to export the file so user can store or backup. I see in original repo `wa-sqlite` the author has a demo for exporting IndexedDB vfs : https://github.com/rhashimoto/wa-sqlite/blob/master/demo/file/service-worker.js

**Comment by khanhicetea** [comment]
My lucky trying :) If you like this idea, I can try to make an PR :)

```ts
    api.export = async (
      cb: (chunk: Uint8Array, offset: number, length: number) => void,
    ) => {
      const fileId = vfs.mapIdToFile.keys().next().value;
      const fileSize = new DataView(new ArrayBuffer(8));
      //const file = vfs.mapIdToFile.get(fileId);
      //await sqlite.close(db);
      //console.log(
      //  "open",
      //  await vfs.jOpen("/IndexedDB.db", fileId, 257, { setInt32() {} }),
      //);
      //console.log("lock", await vfs.jLock(fileId, 1));
      await vfs.jFileSize(fileId, fileSize);
      let iOffset = 0;
      let bytesRemaining = Number(fileSize.getBigUint64(0, true));
      console.log("fileSize = ", bytesRemaining);
      while (bytesRemaining > 0) {
        const buffer = new Uint8Array(Math.min(bytesRemaining, 65536));
        await vfs.jRead(fileId, buffer, iOffset);
        cb(buffer, iOffset, buffer.length);

        iOffset += buffer.byteLength;
        bytesRemaining -= buffer.byteLength;
      }
    };
```

Thanks, have nice day

**Comment by subframe7536** [comment]
Nice work, PR welcome!

And, if you are using `useOpfsStorage`, you can directly download from `OPFS`: The db file has same structure as native filesystem.

**Comment by khanhicetea** [comment]
Yah you're right!

I re-check that my code only work in IndexedDB. I tried to make PR but my TS is weak to wrestling with it + wasm modules :(

**Comment by subframe7536** [comment]
I think it's not your bad. `wa-sqlite` itself is lack of typescript support, and that's one of the main reason why I make this wrapper😅

**Comment by subframe7536** [comment]
Add some type declaration patches

**Comment by khanhicetea** [comment]
Ohhhh so fastttttt 😄 🚀 Thanks, your work saves me weeks for wrestling Wasm thing ^^

Btw, can I invite you a coffee through [AFDIAN](https://afdian.com/)   ? Nice day man

**Comment by subframe7536** [comment]
Thanks for your kindness~ 

https://afdian.com/a/subframe7536

**Comment by khanhicetea** [comment]
Just sent from Paypal, this redirected page is confused. I checked my Paypal then see the successful payment.

<img width="813" alt="image" src="https://github.com/user-attachments/assets/6107c157-51eb-45ef-96d4-55281f31bf0c">

**Comment by subframe7536** [comment]
The "io" seems works, but `import` with `useIDBMemoryStorage` failed due to its VFS implemention.

Upstream: https://github.com/rhashimoto/wa-sqlite/discussions/232

**Comment by khanhicetea** [comment]
Thanks for following this :)
Btw, last time I used IDB vfs, it's not stable yet, I think it has some bugs in upstream, so currently I use Opfs

**Comment by subframe7536** [comment]
Almost complete, waiting for upstream fix

**Comment by khanhicetea** [comment]
Yay, I watching repo and waiting the release :)

**Comment by subframe7536** [comment]
Just copy the source code and fix it in `v0.5.0-beta.2`

**Comment by khanhicetea** [comment]
Niceeee, let me try update my deps and try it :)

**Comment by khanhicetea** [comment]
Btw, just curious, I reading source code of v0.5, without context, this fileId contant looks a bit magic 

https://github.com/subframe7536/sqlite-wasm/blob/main/src/io/import.ts#L88

**Comment by subframe7536** [comment]
Just a copy of the file demo...

https://github.com/rhashimoto/wa-sqlite/blob/3c202615ed6f54ef47610c40281e454dcceb7073/demo/file/index.js#L176

**Comment by subframe7536** [comment]
Release in v0.5.0

**Comment by khanhicetea** [comment]
> Release in v0.5.0

I tested new release in my app, it works okay. Thank you
