### ISSUE TITLE
Wasm file Run time error : memory access out of bounds

### ISSUE THREAD

**Issue by khanhicetea** [subframe7536/sqlite-wasm#2]
Hi, I tried to load the remote wasm file from wa-sqlite (v1.0.4). Then have this error , is this a bug of wasm js scope ?

```ts
const url = "https://cdn.jsdelivr.net/gh/rhashimoto/wa-sqlite@v1.0.4/dist/wa-sqlite-async.wasm"

export default async function initDB() {
  const { run, close, db, sqlite } = await initSQLite(
    useIdbMemoryStorage("test", {
      url: url,
    })
  )
  ///
}
```

<img width="797" alt="image" src="https://github.com/user-attachments/assets/81dffb00-91be-46a5-acf7-3d9f36165c70">

Btw, I tested some query from drizzle, then find out some binded integer (store timestamp as int)  causing memory bug , is there a memory limit like 32 bit int ?

Thanks,

**Comment by khanhicetea** [comment]
I tried load your remote build url , it works. 

```ts
const url = "https://cdn.jsdelivr.net/gh/subframe7536/sqlite-wasm@main/wa-sqlite-fts5/wa-sqlite-async.wasm"
```

Looks like each time we build wasm files, the is a pair files of wasm

`wa-sqlite-async.wasm` and `wa-sqlite-async.mjs` (only this mjs can load this version of .wasm)

**Comment by subframe7536** [comment]
Currently this lib uses a [custom wa-sqlite build](https://github.com/subframe7536/sqwab) to support FTS5 and other features. So the wasm from original project cannot be used.

**Comment by khanhicetea** [comment]
Thanks for clarifying !
