### ISSUE TITLE
`isOpfsSupported` breaks if source is transformed

### ISSUE THREAD

**Issue by davidisaaclee** [subframe7536/sqlite-wasm#3]
`isOpfsSupported` converts a function to a string to create a JS source string https://github.com/subframe7536/sqlite-wasm/blob/08c341a7af1ea2e2cd0db979c781dcf0df00f13f/src/utils.ts#L41-L46 which is then loaded into a worker.

If this code is run through certain code transforms (e.g. `tsc` with target of `es2015`), the `inner` function's string representation can become invalid worker code. In my project, `inner.toString() === 'e'`, so the resulting worker source was `(e)().then(postMessage)` (and `e`'s definition is outside of the worker) – attempting to use `isOpfsSupported` raises an error because `e.then` is not defined.

I think with target = `es2015`, any async function would become invalid: [demo](https://www.typescriptlang.org/play/?target=2&ssl=18&ssc=1&pln=18&pc=3#code/IYZwngdgxgBAZgV2gFwJYHsI1RCBTAJwAoBKGAbwCgYYC9kECtkCE8BuSgX0sqkxDIYADxgBeGAAMiAEnI58BLiQB0wAA7qANmCLIAFqhAAaGMAIBzBAFs8EZCBKTOAegBUlYHGSEYLYBAgcOgE1qaSwpIweACOCMBaIDAg6LYGOBYwWqgA1ngAXLw0RNQ08EhQaJjYuISkFKVltPSMWAD6bcAA7sCoPsTpJjAAbuioACYwAAymoxPTpogoGBBuMPVUTVvNDEx+rByNZcqcTTw0qhrauoOm5la29o68XYZQ+thJOMMJ8wBGeCgwAQIDw2CEdDghDsUDwSQMYPQCGQAFp0HAUSB+OowZIOt1ev1JJQ3C4gA).

---

This is an issue for me because I'm using your `dialect-wasqlite-worker` (which is otherwise great, ty), which has an unskippable check to `isOpfsSupported` when trying to use OPFS.

I don't need a fix urgently because I'm probably just going to patch `dialect-wasqlite-worker` to unblock myself (I can assume OPFS is available in my app), but thought I'd bring this up as a potential pitfall.

**Comment by subframe7536** [comment]
Thanks for reporting! I will fix it later

**Comment by subframe7536** [comment]
Maybe this will works: [link](https://www.typescriptlang.org/play/?target=2#code/KYDwDg9gTgLgBAQwM4E8B2BjOAzArpmASwjTkKQHkxskBlXMSWYAEwAoBKALjgAUoIAW3LAAPACMIEADbAEaAHxwA3gCg4cAPSa4g3EngB3KIRjAchWXBgRrwAwBo4SYOYAWMGGCRdtBhBgA1hAAbsBQ2NIQhgB0GEKaAI649kQkSJoA7ABsAIy5AMwAnAAsAKya2JbAALSoBsCCNQEY9kjNYIQ1JHUI2AgmNcTtGFByZqiYLW1u8iyyNfiBaNFo4QJQQ+pw8WgGZGhrUHAAvHCcPPxCIhJSsvJKJ0prhnwCwi5sbGNIMmEcpyUag0GkI2HOMBQYGAEHBaAQIUIAHMEDYoAB+GIGaAIJHATF4mAAEUIYwwaJQcAAhCczgByPAEYhoOkA4EgjQ-P7ANj9aQuDjbDljGC4KBoIVwAC+qkl8MRKLRWLRuOAMUJJLJFM4ko0MRgbmAaC+AggMABTxUupBYPOVNN5qtHOdcC50jCvIQ-OAgpdwuAovF1o0MuDrqkMHVAYAYtUABJzWRsOkAfQAwnGAKJpgDSdKcyh2Y1RwB4MCgKWlvr9Gm0cAAAjB2qBoeSautoHAVtYocAw3qDUa2LM0PNzJaR2O4sWzLR0BgAIIYVpIJAJ0dJjjVmv6w3G6arwHnA9IOJRT4cJwOmJjQShYCZtDllDJ9NZ3Osrf9uC7oecI9uh65YpF+NZ6hgqIYG4XwWko163vej7Pq+GbZnm25gb+xr-pagE8nyAoYTuEEwFBMEAfY3Ket6W4ON+RFVtacSQdBOFwZR7r4V6hHbFKgrbLayaEIITAwLQoyEGATZ0gccBIlE4hegAKm45BspKIpiqQCCGAgpgHEcOohtsz5Oja4JsJC0KwnAADq0CBOEpy0nAdL4CwwBVGsLAyQAPr5PbWeCVwfOOLluaOnmEN5rJmf6gakARfYcqGHK7PsYrSKccAAKoAEoADLTuMwAUOIABWwDkvlBVsNaLxwAAQgpdU1gA2gABmwAAkyjRUcfGcFhbCQAYACybSqhwHUALp0TWhZWaWrlmCAMCaOVCLIBJUkyVK83OpekoYelRgOU5ZwNfZUCOVAbCZfxaXpPAPy4NI8BnDpenwA1IU3JIMhyIoJocWEV7AJV5KwXFIKGOdUAxCQgiTXi2VsIWLCoggVYUb8nFsJjMAIAxcM3eEiNHBs2XrEebDrDEYBjGET5Ep5CBvTAnDg5DnNJaBIJ8bKHKk7d+rhMI8JmEZII1TewAhBAjllTzNX3VA0iPSCmniq69gc7xOwsTD2uJdxyXSqoUpAA)

**Comment by subframe7536** [comment]
Release in v0.5.0-beta.2

**Comment by davidisaaclee** [comment]
sorry for silence on my end - I applied that change but couldn't figure out if it fixed my problem. (I wasn't able to create a minimal repro.) Thanks for addressing though!

**Comment by subframe7536** [comment]
Release in v0.5.0
