### ISSUE TITLE
Versioning the wasm url (main branch)

### ISSUE THREAD

**Issue by khanhicetea** [subframe7536/sqlite-wasm#4]
Hi, it's not a bug but kindly an issue in future.

Example : The app packaged with version v0.4, try to load the url from main.In the future the main branch link changed another binary wasm, so it's not consistent about DB version. So I think good to mention about this or don't promote using the main url.

Thanks

**Comment by subframe7536** [comment]
Currently, the repo will be auto tagged while publishing a new version, so you can determine the version via tag, like `https://cdn.jsdelivr.net/gh/subframe7536/sqlite-wasm@0.5.0/wa-sqlite-fts5/wa-sqlite.wasm` 

or just use npm version `https://cdn.jsdelivr.net/npm/@subframe7536/sqlite-wasm@0.5.0/wa-sqlite.wasm`

**Comment by khanhicetea** [comment]
Oh I see, I created this because see the example code use main url

<img width="945" alt="image" src="https://github.com/user-attachments/assets/87231ba0-cc29-4f5b-86dd-0c8dd5ce087a" />

**Comment by subframe7536** [comment]
Fixed
